apiVersion: v1
kind: Secret
metadata:
  name: delayed-messaging-secrets
  namespace: default
  labels:
    app: delayed-messaging
    component: backend
    environment: production
    managed-by: kubernetes
    version: 1.0.0
  annotations:
    rotation.kubernetes.io/last-rotated: "2024-02-20T00:00:00Z"
    rotation.kubernetes.io/next-rotation: "2024-03-21T00:00:00Z"
type: Opaque
data:
  # Database Credentials
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQGhvc3Q6NTQzMi9kYXRhYmFzZT9zc2xtb2RlPXJlcXVpcmU= # postgres://user:password@host:5432/database?sslmode=require
  DB_HOST: aG9zdC5yZHMuYW1hem9uYXdzLmNvbQ== # host.rds.amazonaws.com
  DB_PORT: NTQzMg== # 5432
  DB_NAME: ZGVsYXllZF9tZXNzYWdpbmdfcHJvZA== # delayed_messaging_prod
  DB_USER: ZGVsYXllZF9tZXNzYWdpbmdfYXBw # delayed_messaging_app
  DB_PASSWORD: c3Ryb25nX3Byb2RfcGFzc3dvcmQ= # strong_prod_password
  DB_SSL_MODE: cmVxdWlyZQ== # require

  # Redis Credentials
  REDIS_HOST: cmVkaXMuYW1hem9uYXdzLmNvbQ== # redis.amazonaws.com
  REDIS_PORT: NjM3OQ== # 6379
  REDIS_PASSWORD: c3Ryb25nX3JlZGlzX3Bhc3N3b3Jk # strong_redis_password
  REDIS_SSL: dHJ1ZQ== # true
  REDIS_CLUSTER_MODE: dHJ1ZQ== # true

  # Authentication
  JWT_SECRET: c3VwZXJfc2VjcmV0X2p3dF9rZXlfZm9yX3Byb2R1Y3Rpb24= # super_secret_jwt_key_for_production
  JWT_EXPIRY: ODY0MDA= # 86400 (24 hours in seconds)
  REFRESH_TOKEN_SECRET: c3VwZXJfc2VjcmV0X3JlZnJlc2hfdG9rZW5fa2V5X2Zvcl9wcm9kdWN0aW9u # super_secret_refresh_token_key_for_production
  REFRESH_TOKEN_EXPIRY: NjA0ODAwMA== # 604800 (7 days in seconds)
  PASSWORD_SALT_ROUNDS: MTI= # 12

  # Encryption
  ENCRYPTION_KEY: MzJieXRlc19hZXMyNTZfZW5jcnlwdGlvbl9rZXk= # 32bytes_aes256_encryption_key
  ENCRYPTION_IV: MTZieXRlc19pbml0X3Y= # 16bytes_init_v
  ENCRYPTION_ALGORITHM: YWVzLTI1Ni1nY20= # aes-256-gcm
  KEY_ROTATION_INTERVAL: MzBk # 30d

  # External Services
  FCM_SERVER_KEY: ZmlyZWJhc2VfY2xvdWRfbWVzc2FnaW5nX3NlcnZlcl9rZXk= # firebase_cloud_messaging_server_key
  FCM_PROJECT_ID: ZGVsYXllZC1tZXNzYWdpbmctcHJvZA== # delayed-messaging-prod
  SENDGRID_API_KEY: c2VuZGdyaWRfYXBpX2tleV9mb3JfcHJvZHVjdGlvbg== # sendgrid_api_key_for_production
  SENDGRID_FROM_EMAIL: bm9yZXBseUBkZWxheWVkbWVzc2FnaW5nLmNvbQ== # noreply@delayedmessaging.com
  AWS_ACCESS_KEY_ID: QUtJQUlERVhBTVBMRUtFWQ== # AKIAIDEXAMPLEKEY
  AWS_SECRET_ACCESS_KEY: c2VjcmV0X2FjY2Vzc19rZXlfZm9yX2F3c19wcm9kdWN0aW9u # secret_access_key_for_aws_production
  AWS_REGION: dXMtZWFzdC0x # us-east-1

  # Rate Limiting
  RATE_LIMIT_WINDOW: NjAwMDA= # 60000 (1 minute in milliseconds)
  RATE_LIMIT_MAX_REQUESTS: MTAw # 100