# Prometheus configuration file for Delayed Messaging System
# Version: 2.45.0

global:
  scrape_interval: 15s     # Default interval for scraping targets
  evaluation_interval: 15s # Default interval for evaluating rules
  scrape_timeout: 10s     # Timeout for scrape requests

# Scrape configuration for Kubernetes pods
scrape_configs:
  # Auto-discover and scrape Kubernetes pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true

  # Backend API monitoring
  - job_name: 'backend-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend-api:3000']
    metric_relabel_configs:
      # Keep only relevant performance metrics
      - source_labels: [__name__]
        regex: message_delivery_success_rate|message_processing_latency|concurrent_users|system_uptime
        action: keep
    scrape_interval: 15s
    scrape_timeout: 10s

  # Redis monitoring
  - job_name: 'redis'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['redis-exporter:9121']
    metric_relabel_configs:
      # Keep only relevant Redis metrics
      - source_labels: [__name__]
        regex: redis_connected_clients|redis_queue_length|redis_memory_used_bytes
        action: keep
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL monitoring
  - job_name: 'postgresql'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metric_relabel_configs:
      # Keep only relevant PostgreSQL metrics
      - source_labels: [__name__]
        regex: pg_database_size|pg_stat_database_tup_.*|pg_stat_database_xact_commit
        action: keep
    scrape_interval: 15s
    scrape_timeout: 10s

# Alerting configuration
alerting:
  alert_relabel_configs:
    - source_labels: [severity]
      target_label: alert_severity
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Rules files containing alerting rules
rule_files:
  - /etc/prometheus/rules/backend_alerts.yml
  - /etc/prometheus/rules/database_alerts.yml
  - /etc/prometheus/rules/redis_alerts.yml

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention:
      time: 15d
      size: 50GB

# Security configuration
tls_server_config:
  cert_file: /etc/prometheus/certs/prometheus.crt
  key_file: /etc/prometheus/certs/prometheus.key

# HTTP server configuration
web:
  listen_address: 0.0.0.0:9090
  external_url: https://prometheus.delayed-messaging-system.com
  max_connections: 512